language: ruby
rvm:
  - 2.3.0
# branches:
#   only:
#     - source
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
# git:
#   depth: 1
cache:
    bundler: true

gemfile: travisGemfile
before_install:
  - nvm install v6.9.1
  - nvm use v6.9.1
  - npm install -g gulp yarn
install: yarn
script: bundle exec rake travis:script
deploy:
  provider: pages
  local_dir: build
  repo: sagarkrkv/sagarkrkv.github.io
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false
