source 'https://rubygems.org'
ruby '2.3.3'

gem 'middleman', '~> 4.3.11'
gem 'middleman-blog', '~> 4.0.3'
gem 'middleman-syntax'
gem 'middleman-deploy'
gem 'middleman-title'
gem 'middleman-meta-tags'
gem 'middleman-search_engine_sitemap'
gem 'middleman-minify-html'
gem 'middleman-livereload'
gem 'rack-contrib'
gem 'rack-rewrite'
gem 'slim', '4.1.0'
gem 'nokogiri', '1.10.10'
gem 'middleman-autoprefixer'
gem 'sass-media_query_combiner'
gem 'redcarpet'
gem 'rake'
gem 'builder', '~> 3.2'
gem 'bourbon', '~> 7.3'
gem 'sass', '~> 3.7', :require => false
